### ISSUE TITLE
Download images individually

### ISSUE THREAD

**Issue by CuttlefishXuan** [Linxius/UrbanScene3D#10]
Hi, is there a link to download the images individually?  
The NAS link you provided is quite unstable, and the zip files I downloaded many times are invalid. I'm interested in the images in this dataset, can I just download the image data?

**Comment by Linxius** [comment]
You can download the image subdirectories from Dropbox or BaiduYun:
https://www.dropbox.com/sh/8g2urrij2fercko/AABi0GclI-f96uYsAdP0D0Yga?dl=0
https://pan.baidu.com/s/1nqurXpbMzFo_-Cmf6eheOw?pwd=7zdg

**Comment by linhanwang** [comment]
> You can download the image subdirectories from Dropbox or BaiduYun: https://www.dropbox.com/sh/8g2urrij2fercko/AABi0GclI-f96uYsAdP0D0Yga?dl=0 https://pan.baidu.com/s/1nqurXpbMzFo_-Cmf6eheOw?pwd=7zdg

Where are the original drone images in these directories?

**Comment by linhanwang** [comment]
I tried several times. It seems that only one image is corrupted in the zip file, which is photos/119MEDIA/DJI_0057.JPG.

**Comment by Linxius** [comment]
image/ArtSci and image/PolyTech contain multiple sets of drone-captured images.

**Comment by linhanwang** [comment]
> image/ArtSci and image/PolyTech contain multiple sets of drone-captured images.

How can I rebuild UrbanScene3D V1 with data under directory UrbanScene3D-dataset/images, especially Campus.zip? Because when I download Campus.zip? It's always invalid.

**Comment by Linxius** [comment]
Maybe the loaddowned package is corrupted. You can also try to download it from https://pan.baidu.com/s/13OQej3m7rihxwUbGuY9ACQ?pwd=fb7j

**Comment by CuttlefishXuan** [comment]
Sorry for the late reply and thanks for the BaiduYun links! It works!
I have another question about the 3D segmentation data mentioned in the paper Sec.6. How can I acquire the single building models (e.g.meshs)?
I expect to get the single building meshes and corresponding 2d images containing the building, format like the shapenet dataset, for the single-view building reconstruction task. I wonder if the UrbanScene3D dataset supports it.

**Comment by Linxius** [comment]
We only provide building segmentations for the synthetic data in the simulator.
You may try to obtain the segmentations by yourself, with pre-trained segmentation networks or something.

**Comment by CuttlefishXuan** [comment]
> We only provide building segmentations for the synthetic data in the simulator. You may try to obtain the segmentations by yourself, with pre-trained segmentation networks or something.

okay, thank you

**Comment by CuttlefishXuan** [comment]
> We only provide building segmentations for the synthetic data in the simulator. You may try to obtain the segmentations by yourself, with pre-trained segmentation networks or something.

Sorry I'm a little confused, how can I get the single building segmentation results and the labeled object id for the synthetic data? Cause I saw "we manually extract all single building models from the entire scene model" in this paper. Do you have the extracted single building models or do I have to process it myself?

**Comment by Linxius** [comment]
![image](https://github.com/Linxius/UrbanScene3D/assets/17927474/b385cf7a-9910-4383-98bd-c8a826c1d476)
The build model is only provided for certain scenes (see the figure above), which are contained in the simulator https://pan.baidu.com/s/1xkQxYA5XJJp2wIB1BAVVIg?pwd=wz5l
For other scenes like Campus, you need to process it by yourself.

**Comment by CuttlefishXuan** [comment]
Got it, I'll try to install the simulator.

**Comment by pyramidpoint** [comment]
> Maybe the loaddowned package is corrupted. You can also try to download it from

Maybe the link is invalid. Could you provide a new Baidu Cloud address? Thank you!
