### ISSUE TITLE
About Evaluation

### ISSUE THREAD

**Issue by wangyusenofficial** [Linxius/UrbanScene3D#12]
Thank you for providing such a high quality dataset. The google share link about evaluation program has expired, can you provide a new link?

**Comment by Linxius** [comment]
Sorry for the inconvenience. My Google Drive subscription is expired.  Please use the link from [Dropbox](https://www.dropbox.com/home/Storage/UrbanScene3D-Dataset) or [BaiduYun](https://pan.baidu.com/s/1nqurXpbMzFo_-Cmf6eheOw?pwd=7zdg#list/path=%2F).

**Comment by wangyusenofficial** [comment]
Thanks for your reply! I used your latest evaluation protocol to evaluate the Artsci reconstruction result downloaded from the official website.
![aligned](https://github.com/Linxius/UrbanScene3D/assets/72965969/8920be72-c304-4d3e-8b54-b721b81e1e28)
And here is the evaluation results.
![eval](https://github.com/Linxius/UrbanScene3D/assets/72965969/0f53d7a5-ea23-472e-8fca-c9c4fb391e28)
I want to confirm whether this result is reasonable. It seems that the visualization results in fig4 of the paper are better. And do you have any future plans to provide visualization feedback similar to the tanks and temples benchmark?
Looking forward to your reply.

**Comment by Linxius** [comment]
We don't release the original lidar scans due to the copyright. We use much much denser lidar scans for the registration and evaluation in the paper than those provided in the evaluation tool, so the evaluation scores for the real scenes can not reproduced exactly with the provided evaluation tool. 
I don't have the code for some of the evaluated planning algorithms, so it would be hard for me to add more results for other datasets.

**Comment by wangyusenofficial** [comment]
Got it, thank you very much~

**Comment by zwl995** [comment]
> 谢谢你的回复！我使用你们最新的评估协议对从官网下载的 Artsci 重建结果进行了评估。 以下是评估结果。 我想确认一下这个结果是否合理。似乎论文图 4 中的可视化结果更好。你们未来有计划提供类似于 tanks and temples 基准的可视化反馈吗？ 期待你的回复。 ![对齐](https://private-user-images.githubusercontent.com/72965969/291830703-8920be72-c304-4d3e-8b54-b721b81e1e28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA0NDAsIm5iZiI6MTczMTgzMDE0MCwicGF0aCI6Ii83Mjk2NTk2OS8yOTE4MzA3MDMtODkyMGJlNzItYzMwNC00ZDNlLThiNTQtYjcyMWI4MWUxZTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3NTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MTJmYmE4NWM4MzdmZjg0OWI1NDFjZGNkZjY1ZGI1OTdjMmRiZTk3MGM5MGYyNjE2NTRjZTBjODQ5YTA2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6l05QmOzM4zLkKpj-kuigAXy6t-07tGJPIoYxrBRsyI) ![评估](https://private-user-images.githubusercontent.com/72965969/291830774-0f53d7a5-ea23-472e-8fca-c9c4fb391e28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA0NDAsIm5iZiI6MTczMTgzMDE0MCwicGF0aCI6Ii83Mjk2NTk2OS8yOTE4MzA3NzQtMGY1M2Q3YTUtZWEyMy00NzJlLThmY2EtYzljNGZiMzkxZTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3NTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMmQ2MDhhMWI5MmM5NGQ5MzlmMTMzYjdkYjdmOTk3NjE0OWUzNDFkOTRhZmZhMTAwYmE0OWNmYjMzNDhkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nXGdb97zH1YHt7CPBQ09tIuqiw-XHhRLHcge7fRR2eI)

Hello, can I ask you about your operation process? Here's my process:
1.cloudcompare selected points to align its reconstructed model to the very sparse model provided by the author
2. Calculate the conversion relationship using evaluate_model.exe provided by the code to get reg.ply
3. Use reg.ply to calculate accuracy and integrity in evaluate_model.exe in the data interface
Here I have encountered several problems that I cannot understand. It seems that the two evaluation programs are different. One has a printed conversion matrix while the other does not, and the input parameters are inconsistent. The PolyTech scene error seems to be large with a 90% accuracy of 11.2261

**Comment by wangyusenofficial** [comment]
> > 谢谢你的回复！我使用你们最新的评估协议对从官网下载的 Artsci 重建结果进行了评估。 以下是评估结果。 我想确认一下这个结果是否合理。似乎论文图 4 中的可视化结果更好。你们未来有计划提供类似于 tanks and temples 基准的可视化反馈吗？ 期待你的回复。 ![对齐](https://private-user-images.githubusercontent.com/72965969/291830703-8920be72-c304-4d3e-8b54-b721b81e1e28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA0NDAsIm5iZiI6MTczMTgzMDE0MCwicGF0aCI6Ii83Mjk2NTk2OS8yOTE4MzA3MDMtODkyMGJlNzItYzMwNC00ZDNlLThiNTQtYjcyMWI4MWUxZTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3NTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MTJmYmE4NWM4MzdmZjg0OWI1NDFjZGNkZjY1ZGI1OTdjMmRiZTk3MGM5MGYyNjE2NTRjZTBjODQ5YTA2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6l05QmOzM4zLkKpj-kuigAXy6t-07tGJPIoYxrBRsyI) ![评估](https://private-user-images.githubusercontent.com/72965969/291830774-0f53d7a5-ea23-472e-8fca-c9c4fb391e28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA0NDAsIm5iZiI6MTczMTgzMDE0MCwicGF0aCI6Ii83Mjk2NTk2OS8yOTE4MzA3NzQtMGY1M2Q3YTUtZWEyMy00NzJlLThmY2EtYzljNGZiMzkxZTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3NTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMmQ2MDhhMWI5MmM5NGQ5MzlmMTMzYjdkYjdmOTk3NjE0OWUzNDFkOTRhZmZhMTAwYmE0OWNmYjMzNDhkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nXGdb97zH1YHt7CPBQ09tIuqiw-XHhRLHcge7fRR2eI)
> 
> Hello, can I ask you about your operation process? Here's my process: 1.cloudcompare selected points to align its reconstructed model to the very sparse model provided by the author 2. Calculate the conversion relationship using evaluate_model.exe provided by the code to get reg.ply 3. Use reg.ply to calculate accuracy and integrity in evaluate_model.exe in the data interface Here I have encountered several problems that I cannot understand. It seems that the two evaluation programs are different. One has a printed conversion matrix while the other does not, and the input parameters are inconsistent. The PolyTech scene error seems to be large with a 90% accuracy of 11.2261


Similar to your processing steps, we also use CloudCompare to calculate the transformation matrix between the NSR reconstruction result and the GT point cloud. Then, we use the official evaluation program to output the evaluation results. The official program will perform a scale-aware ICP. It's important to note that you need to filter your reconstructed scene using a proxy to remove areas that do not exist in the lidar GT, otherwise, the numerical results will be very poor. For the specific appearance of the proxy, please refer to the supplementary material of [MegaSurf](https://megasurfnsr.github.io/). The metrics used in the MegaSurf paper are directly from the evaluation program provided by Urbanscene3D.

**Comment by zwl995** [comment]
> > > 谢谢你的回复！我用你们最新的评估协议对从网官下载的Artsci重建结果进行了评估。以下是评估结果。我想确认一下这个结果是否合理。似乎图4中的可视化结果更好。你们未来有计划提供坦克和神庙基准的可视化反馈吗？期待你的回复。![康](https://private-user-images.githubusercontent.com/72965969/291830703-8920be72-c304-4d3e-8b54-b721b81e1e28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA0NDAsIm5iZiI6MTczMTgzMDE0MCwicGF0aCI6Ii83Mjk2NTk2OS8yOTE4MzA3MDMtODkyMGJlNzItYzMwNC00ZDNlLThiNTQtYjcyMWI4MWUxZTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3NTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MTJmYmE4NWM4MzdmZjg0OWI1NDFjZGNkZjY1ZGI1OTdjMmRiZTk3MGM5MGYyNjE2NTRjZTBjODQ5YTA2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6l05QmOzM4zLkKpj-kuigAXy6t-07tGJPIoYxrBRsyI) ![项目](https://private-user-images.githubusercontent.com/72965969/291830774-0f53d7a5-ea23-472e-8fca-c9c4fb391e28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA0NDAsIm5iZiI6MTczMTgzMDE0MCwicGF0aCI6Ii83Mjk2NTk2OS8yOTE4MzA3NzQtMGY1M2Q3YTUtZWEyMy00NzJlLThmY2EtYzljNGZiMzkxZTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3NTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMmQ2MDhhMWI5MmM5NGQ5MzlmMTMzYjdkYjdmOTk3NjE0OWUzNDFkOTRhZmZhMTAwYmE0OWNmYjMzNDhkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nXGdb97zH1YHt7CPBQ09tIuqiw-XHhRLHcge7fRR2eI)
> > 
> > 
> > 你好，可以问一下你的操作流程吗？我的流程如下： 1.cloudcompare选取点对齐其重建模型和作者提供的非常稀疏的模型 2.使用代码提供的evaluate_model.exe计算转换关系得到reg.ply 3.使用reg.ply在数据接口中的evaluate_model.exe中计算准确率和完整性 这里遇到了几个看不懂的问题，好像两个评估程序不一样，一个有打印出来的转换矩阵，一个没有，输入的参数也不一致，PolyTech场景误差好像很大，90%准确率是11.2261
> 
> 和您的处理步骤类似，我们也使用CloudCompare计算NSR重建结果和GT点云之间的变换矩阵。然后，我们使用官方的评估程序输出评估结果。官方程序会进行scale-aware ICP。需要注意的是，您需要使用代理过滤重建场景，以删除激光雷达GT中不存在的区域，否则数值结果会很差。有关代理的具体表现，请参考[MegaSurf](https://megasurfnsr.github.io/)的补充材料。MegaSurf论文中使用的指标直接来自Urbanscene3D提供的评估程序。



> > > 谢谢你的回复！我使用你们最新的评估协议对从官网下载的 Artsci 重建结果进行了评估。 以下是评估结果。 我想确认一下这个结果是否合理。似乎论文图 4 中的可视化结果更好。你们未来有计划提供类似于 tanks and temples 基准的可视化反馈吗？ 期待你的回复。 ![对齐](https://private-user-images.githubusercontent.com/72965969/291830703-8920be72-c304-4d3e-8b54-b721b81e1e28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA0NDAsIm5iZiI6MTczMTgzMDE0MCwicGF0aCI6Ii83Mjk2NTk2OS8yOTE4MzA3MDMtODkyMGJlNzItYzMwNC00ZDNlLThiNTQtYjcyMWI4MWUxZTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3NTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MTJmYmE4NWM4MzdmZjg0OWI1NDFjZGNkZjY1ZGI1OTdjMmRiZTk3MGM5MGYyNjE2NTRjZTBjODQ5YTA2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6l05QmOzM4zLkKpj-kuigAXy6t-07tGJPIoYxrBRsyI) ![评估](https://private-user-images.githubusercontent.com/72965969/291830774-0f53d7a5-ea23-472e-8fca-c9c4fb391e28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA0NDAsIm5iZiI6MTczMTgzMDE0MCwicGF0aCI6Ii83Mjk2NTk2OS8yOTE4MzA3NzQtMGY1M2Q3YTUtZWEyMy00NzJlLThmY2EtYzljNGZiMzkxZTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3NTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMmQ2MDhhMWI5MmM5NGQ5MzlmMTMzYjdkYjdmOTk3NjE0OWUzNDFkOTRhZmZhMTAwYmE0OWNmYjMzNDhkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nXGdb97zH1YHt7CPBQ09tIuqiw-XHhRLHcge7fRR2eI)
> > 
> > 
> > Hello, can I ask you about your operation process? Here's my process: 1.cloudcompare selected points to align its reconstructed model to the very sparse model provided by the author 2. Calculate the conversion relationship using evaluate_model.exe provided by the code to get reg.ply 3. Use reg.ply to calculate accuracy and integrity in evaluate_model.exe in the data interface Here I have encountered several problems that I cannot understand. It seems that the two evaluation programs are different. One has a printed conversion matrix while the other does not, and the input parameters are inconsistent. The PolyTech scene error seems to be large with a 90% accuracy of 11.2261
> 
> Similar to your processing steps, we also use CloudCompare to calculate the transformation matrix between the NSR reconstruction result and the GT point cloud. Then, we use the official evaluation program to output the evaluation results. The official program will perform a scale-aware ICP. It's important to note that you need to filter your reconstructed scene using a proxy to remove areas that do not exist in the lidar GT, otherwise, the numerical results will be very poor. For the specific appearance of the proxy, please refer to the supplementary material of [MegaSurf](https://megasurfnsr.github.io/). The metrics used in the MegaSurf paper are directly from the evaluation program provided by Urbanscene3D.

Thank you for your reply. By the way, if you are clipping based on the reconstruction result provided by official data (texture mesh) or sparse GT. Sparse GT. It seems that it is difficult to determine the clipping range, because readme said the.pointcloud file is encrypted, and I couldn't find a good way to visualize it.

**Comment by MegaSurfNsr** [comment]
Currently, you can only get to know the appearance of the GT point cloud from the article. If you need more additional and controllable information, you can pay attention to the recent release of GauUscene V2 by Urbanscene3d.

**Comment by zwl995** [comment]
Okay, I'll pay attention. It seems that the data set link on the homepage is invalid. Maybe it hasn't been opened yet.
