### ISSUE TITLE
Getting the reconstruction .obj files for the real scenes

### ISSUE THREAD

**Issue by OasisArtisan** [Linxius/UrbanScene3D#13]
Hello, thank you for sharing this dataset.

I was wondering if there was a link that I am missing that allows me to download the reconstruction of the real scenes.
Only Artski and polytech .obj files are provided. I am looking for the other 4 real scenes as .obj namely (Residence, Campus, Hospital, Sci-Art, Square).

Are they available somewhere? If not, is it possible to extract their .obj files from the simulator unreal engine project?

Thank you !

**Comment by Linxius** [comment]
Residence, Campus, Hospital, and Square are not maintained now. 
You can download the images (https://github.com/Linxius/UrbanScene3D?tab=readme-ov-file#urbanscene3d-v1) and reconstruct them by yourself.

**Comment by OasisArtisan** [comment]
I see. Thanks
