### ISSUE TITLE
Can I get the camera intrinsics in real city scenes？

### ISSUE THREAD

**Issue by Furenchampion** [Linxius/UrbanScene3D#14]
作者你好，我想利用你的数据集做大场景重建任务，
请问能获取到你采集的真实城市数据集的相机内外参数吗？比如说Square
谢谢

**Comment by Linxius** [comment]
真实场景不同的航次拍的照片用的不同的无人机，相机参数也不一样。你可以跑一下colmap得到对应的内外参。
