### ISSUE TITLE
Get more complete dataset

### ISSUE THREAD

**Issue by Kidleyh** [Linxius/UrbanScene3D#15]
After I downloaded campus, according to the experimental settings of mega-nerf, I found that many images were missing from the campus data set. Has this data set been updated? How can I download a more complete dataset

**Comment by Linxius** [comment]
Do you download it from the links mentioned [here](https://github.com/Linxius/UrbanScene3D?tab=readme-ov-file#urbanscene3d-v1)?

**Comment by Kidleyh** [comment]
Yes, comparing the training settings given by mega-nerf, I found that the pictures I downloaded from here are missing pictures such as 2/DJI_0740.JPG. Many pictures downloaded from here do not have numbers.

**Comment by Linxius** [comment]
You can check if you downloaded the 47.8GB Campus.zip or the 12 zip files correctly.
![image](https://github.com/Linxius/UrbanScene3D/assets/17927474/6c07d43c-838d-4e50-8920-5b7e7814413d)

**Comment by Kidleyh** [comment]
Thank you！Can you tell me how I should download the 12 zip files? I downloaded the entire compressed package before. My computer did remind me that the compressed package was damaged, although I decompressed it successfully.

**Comment by Linxius** [comment]
The entire compressed package should work. Maybe there's something wrong with your downloaded file due to network issues.
https://www.dropbox.com/sh/mg8pvzwmufpfug3/AADK2C8Zrtlf73tNyUvOJJCka?dl=0
https://pan.baidu.com/s/13OQej3m7rihxwUbGuY9ACQ?pwd=fb7j

**Comment by Kidleyh** [comment]
OK, thanks
