### ISSUE TITLE
Scale difference

### ISSUE THREAD

**Issue by rebecca0011** [Linxius/UrbanScene3D#16]
I downloaded and opened the Bridge model and path, but there seemed to be a big difference in the scale of the model and path.
The size of the Bridge model is about 200*150 square meters, while the point cloud dimension occupied by path is about 21000*19000. What's the path unit? What accounts for this difference?

**Comment by Linxius** [comment]
The default units used in the path file are cm (in the Unreal Engine coordinate system).
