### ISSUE TITLE
Chicago Model

### ISSUE THREAD

**Issue by unlugi** [Linxius/UrbanScene3D#4]
Dear Authors,

In the simulator project, Chicago model has a split folder structure with geometry distributed between two folders.

I open the .uasset files for the city inside Unreal Engine(v.4.24) and end up with two splits like this:

![Screenshot 2022-11-22 165351](https://user-images.githubusercontent.com/15035152/203374309-ec9c3809-4fdf-4488-be57-9520fd3e7c41.jpg)
Why are importing like this?

Thank you - and why are they split in the first place?

Also, do you have proxy representations for Chicago (also for other virtual cities)? - like box,coarse,fine etc,

Thank you

**Comment by Linxius** [comment]
Sorry for the delay reply, I didn't notice the issue. 
Is this issue settled?
Chicago looks good on my UE. 
![image](https://user-images.githubusercontent.com/17927474/207798455-db1d7c26-22e8-40bf-92d2-0f41f4b19402.png)
These virtual cities don't come with proxy representations. Actually, they are kind of coarse themselves.

**Comment by Linxius** [comment]
The right way to open it is to open the maps inside content browser of UE. Hope that works.
