### ISSUE TITLE
Questions about the data in the Bridge.

### ISSUE THREAD

**Issue by SunWeiLin-Lynne** [Linxius/UrbanScene3D#5]
Hello, your data set is very impressive. I have some questions for synthetic data Bridge.
First of all, in path files, what are the units of pitch, roll, and yaw? radian measure or angle system? And do they represent the rotation from the world to the camera coordinate system or the rotation from the camera to the world coordinate system?
Secondly, I learned that the units of x, y, z in path files are cm. What are the units of x, y, z in other files, such as. ply files?
Finally, for the Bridge model, what are the camera intrinsic parameters? Can you give the focal length of the camera?
Looking forward to your reply, thank you!

**Comment by Linxius** [comment]
pitch, roll, yaw: angle, they represent the rotation of camera orientation in the camera coordinate. 
The units of x, y, z in other files are m.
