### ISSUE TITLE
Questions about evaluation.

### ISSUE THREAD

**Issue by yxjchly** [Linxius/UrbanScene3D#6]
Hello, what is the definition of accuracy and completeness in evaluation program? How to understand the meaning of evaluation programlogs? Thanks very much!

**Comment by yxjchly** [comment]
Can I reference the two papers, that is _Benchmarking Structure from Motion Algorithms of Urban Environments_and _Tanks and Temples Benchmarking Large Scale Scene Reconstruction_.

**Comment by yxjchly** [comment]
Can I reference the two papers, that is _Benchmarking Structure from Motion Algorithms of Urban Environments_ and _Tanks and Temples Benchmarking Large Scale Scene Reconstruction_.

**Comment by Linxius** [comment]
The value of 90% or 95% accuracy x means that for all the closest points
of the vertices of the reconstruction model on the ground-truth model, 90%
or 95% of them have a distance less than x. The value of 0.02 m, 0.075 m, or
0.075 m completeness x% means that for all the closest points of the vertices
of the ground-truth model on the reconstruction model, x% of them have a
distance less than 0.02 m, 0.05 m, or 0.075 m. A smaller 90% and 95% accuracy
value mean higher accuracy and a larger 0.02 m, 0.05 m, or 0.075 m completeness
value means higher completeness.
