### ISSUE TITLE
An error occurred while opening the Simulator.

### ISSUE THREAD

**Issue by HZhang1003** [Linxius/UrbanScene3D#7]
Your data set has been very helpful to me. Thank you very much.
But an error occurred when I tried to use the Simulator. I opened UrbanScene.uproject in the Simulator folder, but soon got an error: "UrbanScene could not be compliled. Try rebuiding from source mannally."
Could you please tell me how to use the emulator correctly?

**Comment by unlugi** [comment]
Hello! Thank you to the authors for the dataset!
However,  I am having the same problem as above.
I am using UE 4.24 (recommended version of UE), bit I cannot open or compile the project. UrbanScene.uproject
Could you please provide some instructions on how to use the simulator? Thanks.

**Comment by Linxius** [comment]
Have you installed Visual Studio?

**Comment by HZhang1003** [comment]
> 

Yes, I have installed Visual Studio Community 2022, but I still can not run the simulator.

**Comment by Linxius** [comment]
Try to keep Config, Content, Source, and UrbanScene.uproject and delete other files. Then right click on UrbanScene.uproject, generate Virtual Studio project files, open UrbanScene.sln and build from VS. If that works, UrbanScene.uproject can be opened.

**Comment by unlugi** [comment]
@HZhang1003 I just solved my problem and can open the project successfully,
I suggest that you install the following:

1. Unreal Engine 4.24
2. Visual Studio 2017

**Comment by HZhang1003** [comment]
I finally opened the project according to your suggestions. Thank you so much.

**Comment by Greywan** [comment]
> @HZhang1003 I just solved my problem and can open the project successfully, I suggest that you install the following:
> 
> 1. Unreal Engine 4.24
> 2. Visual Studio 2017

Did you install it on windows or linux?

**Comment by Greywan** [comment]
> I finally opened the project according to your suggestions. Thank you so much.

Which Unreal Engine version, please? 4.24？
