### ISSUE TITLE
Dimensions of models in the dataset

### ISSUE THREAD

**Issue by unlugi** [Linxius/UrbanScene3D#9]
Dear author,

Thank you for your great work regarding the dataset.

I am currently using New York, Chicago, Shenzhen etc (the virtual city models) from the dataset.

However, scales of the city models are very different from each other. When imported to Blender together, they are very different scales:
![image](https://user-images.githubusercontent.com/15035152/224092187-8d75a9c3-3f02-4f67-8e43-55ed7b098d1f.png)

Could you please inform me if you know what the size of the citys are in metric dimensions? How much area do they cover? I am trying to discover what one unit corresponds to in metric dimensions in Blender. Or maybe you have some insight on how they were scaled? I couldn't figure it out on my own. 

Thank you for your help in advance.

**Comment by Linxius** [comment]
Usually the height of one floor of a building is about 3 meters. You can scale it according to that.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linxius/UrbanScene3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 凌晨0:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Linxius/UrbanScene3D] Dimensions of models in the dataset (Issue #9)





 
Dear author,
 
Thank you for your great work regarding the dataset.
 
I am currently using New York, Chicago, Shenzhen etc (the virtual city models) from the dataset.
 
However, scales of the city models are very different from each other. When imported to Blender together, they are very different scales:
 
 
Could you please inform me if you know what one unit corresponds to in metric dimensions? Or maybe you have some insight on how they were scaled? I couldn't figure it out on my own.
 
Thank you for your help in advance.

**Comment by Linxius** [comment]
Usually the height of one floor of a building is about 3 meters. You can scale it according to that.
        
    
    
        
            
        
    
    
        
        

        
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Gizem Esra ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/10/2023 00:47
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [Linxius/UrbanScene3D] Dimensions of models in the dataset (Issue #9)
        
      
    
  
  
Dear author,
Thank you for your great work regarding the dataset.
I am currently using New York, Chicago, Shenzhen etc (the virtual city models) from the dataset.
However, scales of the city models are very different from each other. When imported to Blender together, they are very different scales:

Could you please inform me if you know what one unit corresponds to in metric dimensions? Or maybe you have some insight on how they were scaled? I couldn't figure it out on my own.
Thank you for your help in advance.

**Comment by unlugi** [comment]
Okay that is a very good suggestion, thank you!
